
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Workspace
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed class DataWorkspace : global::Microsoft.LightSwitch.Framework.Base.DataWorkspace<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of a DataWorkspace.  Changes can be made to data sources in the new instance independent of changes made to data sources in the default DataWorkspace.
        /// </summary>
        public DataWorkspace() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the TellemData datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.TellemData TellemData
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.TellemData);
            }
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.TellemData;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.TellemData> TellemData
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.TellemData) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.TellemData>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.TellemData>.Entry
                    TellemData = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.TellemData>.Entry(
                        "TellemData",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._TellemData_Stub);
                private static void _TellemData_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.TellemData>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._TellemData, sf);
                }
                 
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.TellemData>.Data _TellemData;
            
        }
    
        #endregion
    }
    
    #endregion
    
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the TellemData datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class TellemData : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public TellemData() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the Companys entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Company> Companys
        {
            get
            {
                return global::LightSwitchApplication.TellemData.DetailsClass.GetValue(this, global::LightSwitchApplication.TellemData.DetailsClass.PropertySetProperties.Companys);
            }
        }
        
        /// <summary>
        /// Gets the Feedbacks entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Feedback> Feedbacks
        {
            get
            {
                return global::LightSwitchApplication.TellemData.DetailsClass.GetValue(this, global::LightSwitchApplication.TellemData.DetailsClass.PropertySetProperties.Feedbacks);
            }
        }
        
        /// <summary>
        /// Gets the Messages entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Message> Messages
        {
            get
            {
                return global::LightSwitchApplication.TellemData.DetailsClass.GetValue(this, global::LightSwitchApplication.TellemData.DetailsClass.PropertySetProperties.Messages);
            }
        }
        
        /// <summary>
        /// Gets the Moods entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Mood> Moods
        {
            get
            {
                return global::LightSwitchApplication.TellemData.DetailsClass.GetValue(this, global::LightSwitchApplication.TellemData.DetailsClass.PropertySetProperties.Moods);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="ID">
        /// The value of the 'ID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Company Companys_Single(global::System.Nullable<int> ID)
        {
            return this.Details.Methods.Companys_Single.CreateInvocation(ID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="ID">
        /// The value of the 'ID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Company Companys_SingleOrDefault(global::System.Nullable<int> ID)
        {
            return this.Details.Methods.Companys_SingleOrDefault.CreateInvocation(ID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="ID">
        /// The value of the 'ID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Feedback Feedbacks_Single(global::System.Nullable<int> ID)
        {
            return this.Details.Methods.Feedbacks_Single.CreateInvocation(ID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="ID">
        /// The value of the 'ID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Feedback Feedbacks_SingleOrDefault(global::System.Nullable<int> ID)
        {
            return this.Details.Methods.Feedbacks_SingleOrDefault.CreateInvocation(ID).Execute();
        }
        
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        public global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Feedback> qryMyFeedback()
        {
            return this.Details.Methods.qryMyFeedback.CreateInvocation().Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="ID">
        /// The value of the 'ID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Message Messages_Single(global::System.Nullable<long> ID)
        {
            return this.Details.Methods.Messages_Single.CreateInvocation(ID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="ID">
        /// The value of the 'ID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Message Messages_SingleOrDefault(global::System.Nullable<long> ID)
        {
            return this.Details.Methods.Messages_SingleOrDefault.CreateInvocation(ID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="ID">
        /// The value of the 'ID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Mood Moods_Single(global::System.Nullable<int> ID)
        {
            return this.Details.Methods.Moods_Single.CreateInvocation(ID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="ID">
        /// The value of the 'ID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Mood Moods_SingleOrDefault(global::System.Nullable<int> ID)
        {
            return this.Details.Methods.Moods_SingleOrDefault.CreateInvocation(ID).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.TellemData.DetailsClass.PropertySet, global::LightSwitchApplication.TellemData.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties.Companys_Single;
                var initializePropertyEntry = global::LightSwitchApplication.TellemData.DetailsClass.PropertySetProperties.Companys;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.TellemData.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.TellemData.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company> Companys_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties.Companys_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company> Companys_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties.Companys_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback> Feedbacks_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties.Feedbacks_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback> Feedbacks_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties.Feedbacks_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback> qryMyFeedback
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties.qryMyFeedback) as global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message> Messages_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties.Messages_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message> Messages_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties.Messages_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood> Moods_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties.Moods_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood> Moods_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties.Moods_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company> Companys
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TellemData.DetailsClass.PropertySetProperties.Companys) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback> Feedbacks
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TellemData.DetailsClass.PropertySetProperties.Feedbacks) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message> Messages
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TellemData.DetailsClass.PropertySetProperties.Messages) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood> Moods
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TellemData.DetailsClass.PropertySetProperties.Moods) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company>.Entry
                    Companys_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company>.Entry(
                        "Companys_Single",
                        global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties._Companys_Single_Stub);
                private static void _Companys_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TellemData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company>.Data> c, global::LightSwitchApplication.TellemData.DetailsClass d, object sf)
                {
                    c(d, ref d._Companys_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company>.Entry
                    Companys_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company>.Entry(
                        "Companys_SingleOrDefault",
                        global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties._Companys_SingleOrDefault_Stub);
                private static void _Companys_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TellemData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company>.Data> c, global::LightSwitchApplication.TellemData.DetailsClass d, object sf)
                {
                    c(d, ref d._Companys_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>.Entry
                    Feedbacks_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>.Entry(
                        "Feedbacks_Single",
                        global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties._Feedbacks_Single_Stub);
                private static void _Feedbacks_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TellemData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>.Data> c, global::LightSwitchApplication.TellemData.DetailsClass d, object sf)
                {
                    c(d, ref d._Feedbacks_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>.Entry
                    Feedbacks_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>.Entry(
                        "Feedbacks_SingleOrDefault",
                        global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties._Feedbacks_SingleOrDefault_Stub);
                private static void _Feedbacks_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TellemData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>.Data> c, global::LightSwitchApplication.TellemData.DetailsClass d, object sf)
                {
                    c(d, ref d._Feedbacks_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>.Entry
                    qryMyFeedback = new global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>.Entry(
                        "qryMyFeedback",
                        global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties._qryMyFeedback_Stub);
                private static void _qryMyFeedback_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TellemData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>.Data> c, global::LightSwitchApplication.TellemData.DetailsClass d, object sf)
                {
                    c(d, ref d._qryMyFeedback, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message>.Entry
                    Messages_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message>.Entry(
                        "Messages_Single",
                        global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties._Messages_Single_Stub);
                private static void _Messages_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TellemData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message>.Data> c, global::LightSwitchApplication.TellemData.DetailsClass d, object sf)
                {
                    c(d, ref d._Messages_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message>.Entry
                    Messages_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message>.Entry(
                        "Messages_SingleOrDefault",
                        global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties._Messages_SingleOrDefault_Stub);
                private static void _Messages_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TellemData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message>.Data> c, global::LightSwitchApplication.TellemData.DetailsClass d, object sf)
                {
                    c(d, ref d._Messages_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood>.Entry
                    Moods_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood>.Entry(
                        "Moods_Single",
                        global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties._Moods_Single_Stub);
                private static void _Moods_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TellemData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood>.Data> c, global::LightSwitchApplication.TellemData.DetailsClass d, object sf)
                {
                    c(d, ref d._Moods_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood>.Entry
                    Moods_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood>.Entry(
                        "Moods_SingleOrDefault",
                        global::LightSwitchApplication.TellemData.DetailsClass.MethodSetProperties._Moods_SingleOrDefault_Stub);
                private static void _Moods_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TellemData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood>.Data> c, global::LightSwitchApplication.TellemData.DetailsClass d, object sf)
                {
                    c(d, ref d._Moods_SingleOrDefault, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company>.Entry
                    Companys = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company>.Entry(
                        "Companys",
                        global::LightSwitchApplication.TellemData.DetailsClass.PropertySetProperties._Companys_Stub);
                private static void _Companys_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TellemData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company>.Data> c, global::LightSwitchApplication.TellemData.DetailsClass d, object sf)
                {
                    c(d, ref d._Companys, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>.Entry
                    Feedbacks = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>.Entry(
                        "Feedbacks",
                        global::LightSwitchApplication.TellemData.DetailsClass.PropertySetProperties._Feedbacks_Stub);
                private static void _Feedbacks_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TellemData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>.Data> c, global::LightSwitchApplication.TellemData.DetailsClass d, object sf)
                {
                    c(d, ref d._Feedbacks, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message>.Entry
                    Messages = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message>.Entry(
                        "Messages",
                        global::LightSwitchApplication.TellemData.DetailsClass.PropertySetProperties._Messages_Stub);
                private static void _Messages_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TellemData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message>.Data> c, global::LightSwitchApplication.TellemData.DetailsClass d, object sf)
                {
                    c(d, ref d._Messages, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood>.Entry
                    Moods = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood>.Entry(
                        "Moods",
                        global::LightSwitchApplication.TellemData.DetailsClass.PropertySetProperties._Moods_Stub);
                private static void _Moods_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TellemData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood>.Data> c, global::LightSwitchApplication.TellemData.DetailsClass d, object sf)
                {
                    c(d, ref d._Moods, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company>.Data _Companys;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>.Data _Feedbacks;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message>.Data _Messages;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood>.Data _Moods;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company>.Data _Companys_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Company>.Data _Companys_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>.Data _Feedbacks_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>.Data _Feedbacks_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Feedback>.Data _qryMyFeedback;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message>.Data _Messages_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Message>.Data _Messages_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood>.Data _Moods_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.TellemData, global::LightSwitchApplication.TellemData.DetailsClass, global::LightSwitchApplication.Mood>.Data _Moods_SingleOrDefault;
            
        }
    
        #endregion
    }
    
    #endregion
    
}
