//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region Company
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/TellemData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Company :
        global::LightSwitchApplication.Company.DetailsClass.IImplementation
    {
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnCompany_NameChanged()
        {
            this.___OnPropertyChanged("Company_Name");
        }
        
        partial void OnLongitudeChanged()
        {
            this.___OnPropertyChanged("Longitude");
        }
        
        partial void OnLatitudeChanged()
        {
            this.___OnPropertyChanged("Latitude");
        }
        
        partial void OnActiveChanged()
        {
            this.___OnPropertyChanged("Active");
        }
        
    }
    #endregion
    
    #region Feedback
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/TellemData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Feedback :
        global::LightSwitchApplication.Feedback.DetailsClass.IImplementation
    {
        partial void OnMoodChanged()
        {
            this.___OnPropertyChanged("Mood");
            this.___OnPropertyChanged("Mood1");
        }
        
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnCompanyChanged()
        {
            this.___OnPropertyChanged("Company");
        }
        
        partial void OnLocationChanged()
        {
            this.___OnPropertyChanged("Location");
        }
        
        partial void OnEmployeeChanged()
        {
            this.___OnPropertyChanged("Employee");
        }
        
        partial void OnCommentChanged()
        {
            this.___OnPropertyChanged("Comment");
        }
        
        partial void OnUserIDChanged()
        {
            this.___OnPropertyChanged("UserID");
        }
        
        partial void OnDateCreatedChanged()
        {
            this.___OnPropertyChanged("DateCreated");
        }
        
        partial void OnProductChanged()
        {
            this.___OnPropertyChanged("Product");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Feedback.DetailsClass.IImplementation.Mood1
        {
            get
            {
                return this.Mood1;
            }
            set
            {
                this.Mood1 = (global::LightSwitchApplication.Implementation.Mood)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Mood> __Mood1
        {
            get
            {
                if (this.___Mood1 == null)
                {
                    this.___Mood1 = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Mood>(
                        this,
                        "Mood1",
                        new string[] { "Mood" },
                        e => global::System.Object.Equals(e.ID, this.Mood),
                        () => this._Mood1,
                        e => this._Mood1 = e);
                }
                return this.___Mood1;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Mood> ___Mood1;
        
    }
    #endregion
    
    #region Message
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/TellemData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Message :
        global::LightSwitchApplication.Message.DetailsClass.IImplementation
    {
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnMessageNameChanged()
        {
            this.___OnPropertyChanged("MessageName");
        }
        
        partial void OnMessage1Changed()
        {
            this.___OnPropertyChanged("Message1");
        }
        
    }
    #endregion
    
    #region Mood
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/TellemData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Mood :
        global::LightSwitchApplication.Mood.DetailsClass.IImplementation
    {
        partial void OnIDChanged()
        {
            this.___OnPropertyChanged("ID");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        partial void OnEmoticonChanged()
        {
            this.___OnPropertyChanged("Emoticon");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Mood.DetailsClass.IImplementation.Feedbacks
        {
            get
            {
                return this.Feedbacks;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Feedback> __Feedbacks
        {
            get
            {
                if (this.___Feedbacks == null)
                {
                    this.___Feedbacks = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Feedback>(
                        this,
                        "Feedbacks",
                        () => this._Feedbacks,
                        e => global::System.Object.Equals(e.Mood, this.ID));
                }
                return this.___Feedbacks;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Feedback> ___Feedbacks;
        
    }
    #endregion
    
    #region TellemData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TellemData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Company))
            {
                return new global::LightSwitchApplication.Implementation.Company();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Feedback))
            {
                return new global::LightSwitchApplication.Implementation.Feedback();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Message))
            {
                return new global::LightSwitchApplication.Implementation.Message();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Mood))
            {
                return new global::LightSwitchApplication.Implementation.Mood();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.TellemData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.TellemData))
            {
                return new global::LightSwitchApplication.TellemData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.TellemData))
            {
                return new global::LightSwitchApplication.Implementation.TellemData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../TellemData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Company) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Company);
            }
            if (typeof(global::LightSwitchApplication.Feedback) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Feedback);
            }
            if (typeof(global::LightSwitchApplication.Message) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Message);
            }
            if (typeof(global::LightSwitchApplication.Mood) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Mood);
            }
            return null;
        }
    }
}
