

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class Company : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Company entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Company()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Company(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Company> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Company.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Company_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Company_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID
        {
            get
            {
                return global::LightSwitchApplication.Company.DetailsClass.GetValue(this, global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties.ID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Company_Name
        {
            get
            {
                return global::LightSwitchApplication.Company.DetailsClass.GetValue(this, global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties.Company_Name);
            }
            set
            {
                global::LightSwitchApplication.Company.DetailsClass.SetValue(this, global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties.Company_Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Company_Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Company_Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Company_Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<double> Longitude
        {
            get
            {
                return global::LightSwitchApplication.Company.DetailsClass.GetValue(this, global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties.Longitude);
            }
            set
            {
                global::LightSwitchApplication.Company.DetailsClass.SetValue(this, global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties.Longitude, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Longitude_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Longitude_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Longitude_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<double> Latitude
        {
            get
            {
                return global::LightSwitchApplication.Company.DetailsClass.GetValue(this, global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties.Latitude);
            }
            set
            {
                global::LightSwitchApplication.Company.DetailsClass.SetValue(this, global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties.Latitude, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Latitude_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Latitude_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Latitude_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> Active
        {
            get
            {
                return global::LightSwitchApplication.Company.DetailsClass.GetValue(this, global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties.Active);
            }
            set
            {
                global::LightSwitchApplication.Company.DetailsClass.SetValue(this, global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties.Active, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Active_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Active_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Active_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Company,
                global::LightSwitchApplication.Company.DetailsClass,
                global::LightSwitchApplication.Company.DetailsClass.IImplementation,
                global::LightSwitchApplication.Company.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties.ID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass>.Entry
                __CompanyEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass>.Entry(
                    global::LightSwitchApplication.Company.DetailsClass.__Company_CreateNew,
                    global::LightSwitchApplication.Company.DetailsClass.__Company_Created,
                    global::LightSwitchApplication.Company.DetailsClass.__Company_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Company __Company_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Company> es)
            {
                return new global::LightSwitchApplication.Company(es);
            }
            private static void __Company_Created(global::LightSwitchApplication.Company e)
            {
                e.Company_Created();
            }
            private static bool __Company_AllowSaveWithErrors(global::LightSwitchApplication.Company e)
            {
                bool result = false;
                e.Company_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Company.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, int> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, string> Company_Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties.Company_Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<double>> Longitude
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties.Longitude) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<double>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<double>> Latitude
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties.Latitude) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<double>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<bool>> Active
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties.Active) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ID { get; }
                new string Company_Name { get; set; }
                new global::System.Nullable<double> Longitude { get; set; }
                new global::System.Nullable<double> Latitude { get; set; }
                new global::System.Nullable<bool> Active { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, int>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, int>.Entry(
                        "ID",
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Company.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, int>.Data> c, global::LightSwitchApplication.Company.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.Company e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.Company e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static int _ID_GetImplementationValue(global::LightSwitchApplication.Company.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.Company e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, string>.Entry
                    Company_Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, string>.Entry(
                        "Company_Name",
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Company_Name_Stub,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Company_Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Company_Name_Validate,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Company_Name_GetImplementationValue,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Company_Name_SetImplementationValue,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Company_Name_OnValueChanged);
                private static void _Company_Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Company.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, string>.Data> c, global::LightSwitchApplication.Company.DetailsClass d, object sf)
                {
                    c(d, ref d._Company_Name, sf);
                }
                private static bool _Company_Name_ComputeIsReadOnly(global::LightSwitchApplication.Company e)
                {
                    bool result = false;
                    e.Company_Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Company_Name_Validate(global::LightSwitchApplication.Company e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Company_Name_Validate(r);
                }
                private static string _Company_Name_GetImplementationValue(global::LightSwitchApplication.Company.DetailsClass d)
                {
                    return d.ImplementationEntity.Company_Name;
                }
                private static void _Company_Name_SetImplementationValue(global::LightSwitchApplication.Company.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Company_Name = v;
                }
                private static void _Company_Name_OnValueChanged(global::LightSwitchApplication.Company e)
                {
                    e.Company_Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<double>>.Entry
                    Longitude = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<double>>.Entry(
                        "Longitude",
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Longitude_Stub,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Longitude_ComputeIsReadOnly,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Longitude_Validate,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Longitude_GetImplementationValue,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Longitude_SetImplementationValue,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Longitude_OnValueChanged);
                private static void _Longitude_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Company.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<double>>.Data> c, global::LightSwitchApplication.Company.DetailsClass d, object sf)
                {
                    c(d, ref d._Longitude, sf);
                }
                private static bool _Longitude_ComputeIsReadOnly(global::LightSwitchApplication.Company e)
                {
                    bool result = false;
                    e.Longitude_IsReadOnly(ref result);
                    return result;
                }
                private static void _Longitude_Validate(global::LightSwitchApplication.Company e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Longitude_Validate(r);
                }
                private static global::System.Nullable<double> _Longitude_GetImplementationValue(global::LightSwitchApplication.Company.DetailsClass d)
                {
                    return d.ImplementationEntity.Longitude;
                }
                private static void _Longitude_SetImplementationValue(global::LightSwitchApplication.Company.DetailsClass d, global::System.Nullable<double> v)
                {
                    d.ImplementationEntity.Longitude = v;
                }
                private static void _Longitude_OnValueChanged(global::LightSwitchApplication.Company e)
                {
                    e.Longitude_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<double>>.Entry
                    Latitude = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<double>>.Entry(
                        "Latitude",
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Latitude_Stub,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Latitude_ComputeIsReadOnly,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Latitude_Validate,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Latitude_GetImplementationValue,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Latitude_SetImplementationValue,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Latitude_OnValueChanged);
                private static void _Latitude_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Company.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<double>>.Data> c, global::LightSwitchApplication.Company.DetailsClass d, object sf)
                {
                    c(d, ref d._Latitude, sf);
                }
                private static bool _Latitude_ComputeIsReadOnly(global::LightSwitchApplication.Company e)
                {
                    bool result = false;
                    e.Latitude_IsReadOnly(ref result);
                    return result;
                }
                private static void _Latitude_Validate(global::LightSwitchApplication.Company e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Latitude_Validate(r);
                }
                private static global::System.Nullable<double> _Latitude_GetImplementationValue(global::LightSwitchApplication.Company.DetailsClass d)
                {
                    return d.ImplementationEntity.Latitude;
                }
                private static void _Latitude_SetImplementationValue(global::LightSwitchApplication.Company.DetailsClass d, global::System.Nullable<double> v)
                {
                    d.ImplementationEntity.Latitude = v;
                }
                private static void _Latitude_OnValueChanged(global::LightSwitchApplication.Company e)
                {
                    e.Latitude_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<bool>>.Entry
                    Active = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "Active",
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Active_Stub,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Active_ComputeIsReadOnly,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Active_Validate,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Active_GetImplementationValue,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Active_SetImplementationValue,
                        global::LightSwitchApplication.Company.DetailsClass.PropertySetProperties._Active_OnValueChanged);
                private static void _Active_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Company.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.Company.DetailsClass d, object sf)
                {
                    c(d, ref d._Active, sf);
                }
                private static bool _Active_ComputeIsReadOnly(global::LightSwitchApplication.Company e)
                {
                    bool result = false;
                    e.Active_IsReadOnly(ref result);
                    return result;
                }
                private static void _Active_Validate(global::LightSwitchApplication.Company e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Active_Validate(r);
                }
                private static global::System.Nullable<bool> _Active_GetImplementationValue(global::LightSwitchApplication.Company.DetailsClass d)
                {
                    return d.ImplementationEntity.Active;
                }
                private static void _Active_SetImplementationValue(global::LightSwitchApplication.Company.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.Active = v;
                }
                private static void _Active_OnValueChanged(global::LightSwitchApplication.Company e)
                {
                    e.Active_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, int>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, string>.Data _Company_Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<double>>.Data _Longitude;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<double>>.Data _Latitude;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass, global::System.Nullable<bool>>.Data _Active;
            
        }
    
        #endregion
    }
    
    #endregion
}
