//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class MoodsListDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private MoodsListDetail() : base("LightSwitchApplication.TellemCSharp.DesktopClient:MoodsListDetail")
        {
            global::LightSwitchApplication.MoodsListDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static MoodsListDetail CreateInstance()
        {
            return new global::LightSwitchApplication.MoodsListDetail(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MoodsListDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MoodsListDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MoodsListDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MoodsListDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MoodsListDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MoodsListDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MoodsListDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Moods_SelectionChanged();

        partial void Moods_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Moods_Loaded(bool succeeded);

        partial void Feedbacks_SelectionChanged();

        partial void Feedbacks_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Feedbacks_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Moods visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Mood> Moods
        {
            get
            {
                return global::LightSwitchApplication.MoodsListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySetProperties.Moods);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Moods_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the Feedbacks visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Feedback> Feedbacks
        {
            get
            {
                return global::LightSwitchApplication.MoodsListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySetProperties.Feedbacks);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Feedbacks_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass, global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySet, global::LightSwitchApplication.MoodsListDetail.DetailsClass.CommandSet, global::LightSwitchApplication.MoodsListDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySetProperties.Moods;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass>.Entry
                __MoodsListDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.MoodsListDetail.DetailsClass.__MoodsListDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.MoodsListDetail.DetailsClass.__MoodsListDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.MoodsListDetail.DetailsClass.__MoodsListDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.MoodsListDetail.DetailsClass.__MoodsListDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.MoodsListDetail.DetailsClass.__MoodsListDetail_InvokeCreated,
                    global::LightSwitchApplication.MoodsListDetail.DetailsClass.__MoodsListDetail_InvokeActivated,
                    global::LightSwitchApplication.MoodsListDetail.DetailsClass.__MoodsListDetail_InvokeSaveErrorEvent);
            private static void __MoodsListDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.MoodsListDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.MoodsListDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __MoodsListDetail_InvokeSavingEvent(global::LightSwitchApplication.MoodsListDetail s)
            {
                bool handled = false;
                s.MoodsListDetail_Saving(ref handled);
                return handled;
            }
            private static void __MoodsListDetail_InvokeSavedEvent(global::LightSwitchApplication.MoodsListDetail s)
            {
                s.MoodsListDetail_Saved();
            }
            private static bool __MoodsListDetail_InvokeClosingEvent(global::LightSwitchApplication.MoodsListDetail s)
            {
                bool cancel = false;
                s.MoodsListDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __MoodsListDetail_InvokeCreated(global::LightSwitchApplication.MoodsListDetail s)
            {
                s.MoodsListDetail_Created();
            }
            private static void __MoodsListDetail_InvokeActivated(global::LightSwitchApplication.MoodsListDetail s)
            {
                s.MoodsListDetail_Activated();
            }
            private static bool __MoodsListDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.MoodsListDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.MoodsListDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.MoodsListDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.MoodsListDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable MoodsQuery()
            {
                return this.Screen.DataWorkspace.TellemData.Moods;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable FeedbacksQuery()
            {
                if (this.Screen.Moods.SelectedItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Feedback> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Feedback>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.Moods.SelectedItem.Details.Properties.Feedbacks).Loader;
                if (loader == null)
                {
                    return null;
                }

                return loader;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass, global::LightSwitchApplication.Mood>.Data _Moods;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass, global::LightSwitchApplication.Feedback>.Data _Feedbacks;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass, global::LightSwitchApplication.Mood> Moods
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass, global::LightSwitchApplication.Mood>)base.GetItem(global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySetProperties.Moods);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass, global::LightSwitchApplication.Feedback> Feedbacks
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass, global::LightSwitchApplication.Feedback>)base.GetItem(global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySetProperties.Feedbacks);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass, global::LightSwitchApplication.Mood>.Entry
                    Moods = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass, global::LightSwitchApplication.Mood>.Entry(
                        "Moods",
                        global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySetProperties._Moods_Stub,
                        global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySetProperties._Moods_Validate,
                        global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySetProperties._Moods_CreateQuery,
                        global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySetProperties._Moods_SelectionChanged,
                        global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySetProperties._Moods_OnCollectionChanged,
                        global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySetProperties._Moods_OnLoaded);
                private static void _Moods_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MoodsListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass, global::LightSwitchApplication.Mood>.Data> c, global::LightSwitchApplication.MoodsListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Moods, sf);
                }
                private static void _Moods_Validate(global::LightSwitchApplication.MoodsListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Moods_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Moods_CreateQuery(global::LightSwitchApplication.MoodsListDetail.DetailsClass d, object[] args)
                {
                    return d.MoodsQuery();
                }
                private static void _Moods_SelectionChanged(global::LightSwitchApplication.MoodsListDetail s)
                {
                    s.Moods_SelectionChanged();
                }
                private static void _Moods_OnCollectionChanged(global::LightSwitchApplication.MoodsListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Moods_Changed(e);
                }
                private static void _Moods_OnLoaded(global::LightSwitchApplication.MoodsListDetail s, bool succeeded)
                {
                    s.Moods_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass, global::LightSwitchApplication.Feedback>.Entry
                    Feedbacks = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass, global::LightSwitchApplication.Feedback>.Entry(
                        "Feedbacks",
                        global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySetProperties._Feedbacks_Stub,
                        global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySetProperties._Feedbacks_Validate,
                        global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySetProperties._Feedbacks_CreateQuery,
                        global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySetProperties._Feedbacks_SelectionChanged,
                        global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySetProperties._Feedbacks_OnCollectionChanged,
                        global::LightSwitchApplication.MoodsListDetail.DetailsClass.PropertySetProperties._Feedbacks_OnLoaded);
                private static void _Feedbacks_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MoodsListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MoodsListDetail, global::LightSwitchApplication.MoodsListDetail.DetailsClass, global::LightSwitchApplication.Feedback>.Data> c, global::LightSwitchApplication.MoodsListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Feedbacks, sf);
                }
                private static void _Feedbacks_Validate(global::LightSwitchApplication.MoodsListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Feedbacks_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Feedbacks_CreateQuery(global::LightSwitchApplication.MoodsListDetail.DetailsClass d, object[] args)
                {
                    return d.FeedbacksQuery();
                }
                private static void _Feedbacks_SelectionChanged(global::LightSwitchApplication.MoodsListDetail s)
                {
                    s.Feedbacks_SelectionChanged();
                }
                private static void _Feedbacks_OnCollectionChanged(global::LightSwitchApplication.MoodsListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Feedbacks_Changed(e);
                }
                private static void _Feedbacks_OnLoaded(global::LightSwitchApplication.MoodsListDetail s, bool succeeded)
                {
                    s.Feedbacks_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
