//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 5/04/2015 10:24:04 AM
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// There are no comments for TellemData in the schema.
    /// </summary>
    public partial class TellemData : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// Initialize a new TellemData object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public TellemData(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "LightSwitchApplication", "LightSwitchApplication.Implementation");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Companys in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Company> Companys
        {
            get
            {
                if ((this._Companys == null))
                {
                    this._Companys = base.CreateQuery<Company>("Companys");
                }
                return this._Companys;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Company> _Companys;
        /// <summary>
        /// There are no comments for Feedbacks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Feedback> Feedbacks
        {
            get
            {
                if ((this._Feedbacks == null))
                {
                    this._Feedbacks = base.CreateQuery<Feedback>("Feedbacks");
                }
                return this._Feedbacks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Feedback> _Feedbacks;
        /// <summary>
        /// There are no comments for Messages in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Message> Messages
        {
            get
            {
                if ((this._Messages == null))
                {
                    this._Messages = base.CreateQuery<Message>("Messages");
                }
                return this._Messages;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Message> _Messages;
        /// <summary>
        /// There are no comments for Moods in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Mood> Moods
        {
            get
            {
                if ((this._Moods == null))
                {
                    this._Moods = base.CreateQuery<Mood>("Moods");
                }
                return this._Moods;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Mood> _Moods;
        /// <summary>
        /// There are no comments for Companys in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCompanys(Company company)
        {
            base.AddObject("Companys", company);
        }
        /// <summary>
        /// There are no comments for Feedbacks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFeedbacks(Feedback feedback)
        {
            base.AddObject("Feedbacks", feedback);
        }
        /// <summary>
        /// There are no comments for Messages in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMessages(Message message)
        {
            base.AddObject("Messages", message);
        }
        /// <summary>
        /// There are no comments for Moods in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMoods(Mood mood)
        {
            base.AddObject("Moods", mood);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataserv" +
                "ices/metadata\" m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\"><Schema " +
                "xmlns:annotation=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" Names" +
                "pace=\"LightSwitchApplication\" Alias=\"Self\" xmlns=\"http://schemas.microsoft.com/a" +
                "do/2008/09/edm\"><EntityType Name=\"Company\"><Key><PropertyRef Name=\"ID\" /></Key><" +
                "Property Name=\"ID\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPa" +
                "ttern=\"Identity\" /><Property Name=\"Company_Name\" Type=\"Edm.String\" MaxLength=\"10" +
                "0\" ConcurrencyMode=\"Fixed\" /><Property Name=\"Longitude\" Type=\"Edm.Double\" /><Pro" +
                "perty Name=\"Latitude\" Type=\"Edm.Double\" /><Property Name=\"Active\" Type=\"Edm.Bool" +
                "ean\" ConcurrencyMode=\"Fixed\" /></EntityType><EntityType Name=\"Feedback\"><Key><Pr" +
                "opertyRef Name=\"ID\" /></Key><Property Name=\"ID\" Type=\"Edm.Int32\" Nullable=\"false" +
                "\" annotation:StoreGeneratedPattern=\"Identity\" /><Property Name=\"Company\" Type=\"E" +
                "dm.String\" MaxLength=\"100\" ConcurrencyMode=\"Fixed\" /><Property Name=\"Location\" T" +
                "ype=\"Edm.String\" MaxLength=\"100\" ConcurrencyMode=\"Fixed\" /><Property Name=\"Emplo" +
                "yee\" Type=\"Edm.String\" MaxLength=\"100\" ConcurrencyMode=\"Fixed\" /><Property Name=" +
                "\"Comment\" Type=\"Edm.String\" MaxLength=\"Max\" Unicode=\"false\" /><Property Name=\"Us" +
                "erID\" Type=\"Edm.String\" MaxLength=\"50\" ConcurrencyMode=\"Fixed\" /><Property Name=" +
                "\"DateCreated\" Type=\"Edm.DateTime\" Precision=\"3\" ConcurrencyMode=\"Fixed\" /><Prope" +
                "rty Name=\"Mood\" Type=\"Edm.Int32\" ConcurrencyMode=\"Fixed\" /><Property Name=\"Produ" +
                "ct\" Type=\"Edm.String\" MaxLength=\"Max\" ConcurrencyMode=\"Fixed\" /><NavigationPrope" +
                "rty Name=\"Mood1\" Relationship=\"LightSwitchApplication.FK_Feedback_Mood\" ToRole=\"" +
                "Mood\" FromRole=\"Feedback\" /></EntityType><EntityType Name=\"Message\"><Key><Proper" +
                "tyRef Name=\"ID\" /></Key><Property Name=\"ID\" Type=\"Edm.Int64\" Nullable=\"false\" an" +
                "notation:StoreGeneratedPattern=\"Identity\" /><Property Name=\"MessageName\" Type=\"E" +
                "dm.String\" MaxLength=\"Max\" ConcurrencyMode=\"Fixed\" /><Property Name=\"Message1\" T" +
                "ype=\"Edm.String\" MaxLength=\"Max\" ConcurrencyMode=\"Fixed\" /></EntityType><EntityT" +
                "ype Name=\"Mood\"><Key><PropertyRef Name=\"ID\" /></Key><Property Name=\"ID\" Type=\"Ed" +
                "m.Int32\" Nullable=\"false\" /><Property Name=\"Description\" Type=\"Edm.String\" MaxLe" +
                "ngth=\"100\" ConcurrencyMode=\"Fixed\" /><Property Name=\"Emoticon\" Type=\"Edm.Binary\"" +
                " MaxLength=\"Max\" /><NavigationProperty Name=\"Feedbacks\" Relationship=\"LightSwitc" +
                "hApplication.FK_Feedback_Mood\" ToRole=\"Feedback\" FromRole=\"Mood\" /></EntityType>" +
                "<Association Name=\"FK_Feedback_Mood\"><End Role=\"Mood\" Type=\"LightSwitchApplicati" +
                "on.Mood\" Multiplicity=\"0..1\" /><End Role=\"Feedback\" Type=\"LightSwitchApplication" +
                ".Feedback\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Mood\"><Pro" +
                "pertyRef Name=\"ID\" /></Principal><Dependent Role=\"Feedback\"><PropertyRef Name=\"M" +
                "ood\" /></Dependent></ReferentialConstraint></Association><EntityContainer Name=\"" +
                "TellemData\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Companys\" EntityT" +
                "ype=\"LightSwitchApplication.Company\" /><EntitySet Name=\"Feedbacks\" EntityType=\"L" +
                "ightSwitchApplication.Feedback\" /><EntitySet Name=\"Messages\" EntityType=\"LightSw" +
                "itchApplication.Message\" /><EntitySet Name=\"Moods\" EntityType=\"LightSwitchApplic" +
                "ation.Mood\" /><AssociationSet Name=\"FK_Feedback_Mood\" Association=\"LightSwitchAp" +
                "plication.FK_Feedback_Mood\"><End Role=\"Mood\" EntitySet=\"Moods\" /><End Role=\"Feed" +
                "back\" EntitySet=\"Feedbacks\" /></AssociationSet><FunctionImport Name=\"qryMyFeedba" +
                "ck\" ReturnType=\"Collection(LightSwitchApplication.Feedback)\" EntitySet=\"Feedback" +
                "s\" m:HttpMethod=\"GET\" /><FunctionImport Name=\"Microsoft_LightSwitch_GetCanInform" +
                "ation\" ReturnType=\"Edm.String\" m:HttpMethod=\"GET\"><Parameter Name=\"dataServiceMe" +
                "mbers\" Type=\"Edm.String\" Mode=\"In\" /></FunctionImport></EntityContainer></Schema" +
                "></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Company in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Companys")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Company : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Company CreateCompany(int ID)
        {
            Company company = new Company();
            company.ID = ID;
            return company;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                if (object.Equals(this.ID, value))
                {
                    return;
                }
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Company_Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Company_Name
        {
            get
            {
                return this._Company_Name;
            }
            set
            {
                this.OnCompany_NameChanging(value);
                if (object.Equals(this.Company_Name, value))
                {
                    return;
                }
                this._Company_Name = value;
                this.OnCompany_NameChanged();
                this.OnPropertyChanged("Company_Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Company_Name;
        partial void OnCompany_NameChanging(string value);
        partial void OnCompany_NameChanged();
        /// <summary>
        /// There are no comments for Property Longitude in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<double> Longitude
        {
            get
            {
                return this._Longitude;
            }
            set
            {
                this.OnLongitudeChanging(value);
                if (object.Equals(this.Longitude, value))
                {
                    return;
                }
                this._Longitude = value;
                this.OnLongitudeChanged();
                this.OnPropertyChanged("Longitude");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<double> _Longitude;
        partial void OnLongitudeChanging(global::System.Nullable<double> value);
        partial void OnLongitudeChanged();
        /// <summary>
        /// There are no comments for Property Latitude in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<double> Latitude
        {
            get
            {
                return this._Latitude;
            }
            set
            {
                this.OnLatitudeChanging(value);
                if (object.Equals(this.Latitude, value))
                {
                    return;
                }
                this._Latitude = value;
                this.OnLatitudeChanged();
                this.OnPropertyChanged("Latitude");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<double> _Latitude;
        partial void OnLatitudeChanging(global::System.Nullable<double> value);
        partial void OnLatitudeChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                if (object.Equals(this.Active, value))
                {
                    return;
                }
                this._Active = value;
                this.OnActiveChanged();
                this.OnPropertyChanged("Active");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _Active;
        partial void OnActiveChanging(global::System.Nullable<bool> value);
        partial void OnActiveChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Feedback in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Feedbacks")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Feedback : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Feedback object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Feedback CreateFeedback(int ID)
        {
            Feedback feedback = new Feedback();
            feedback.ID = ID;
            return feedback;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                if (object.Equals(this.ID, value))
                {
                    return;
                }
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Company in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Company
        {
            get
            {
                return this._Company;
            }
            set
            {
                this.OnCompanyChanging(value);
                if (object.Equals(this.Company, value))
                {
                    return;
                }
                this._Company = value;
                this.OnCompanyChanged();
                this.OnPropertyChanged("Company");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Company;
        partial void OnCompanyChanging(string value);
        partial void OnCompanyChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                if (object.Equals(this.Location, value))
                {
                    return;
                }
                this._Location = value;
                this.OnLocationChanged();
                this.OnPropertyChanged("Location");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Location;
        partial void OnLocationChanging(string value);
        partial void OnLocationChanged();
        /// <summary>
        /// There are no comments for Property Employee in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Employee
        {
            get
            {
                return this._Employee;
            }
            set
            {
                this.OnEmployeeChanging(value);
                if (object.Equals(this.Employee, value))
                {
                    return;
                }
                this._Employee = value;
                this.OnEmployeeChanged();
                this.OnPropertyChanged("Employee");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Employee;
        partial void OnEmployeeChanging(string value);
        partial void OnEmployeeChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                if (object.Equals(this.Comment, value))
                {
                    return;
                }
                this._Comment = value;
                this.OnCommentChanged();
                this.OnPropertyChanged("Comment");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Property UserID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                this.OnUserIDChanging(value);
                if (object.Equals(this.UserID, value))
                {
                    return;
                }
                this._UserID = value;
                this.OnUserIDChanged();
                this.OnPropertyChanged("UserID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserID;
        partial void OnUserIDChanging(string value);
        partial void OnUserIDChanged();
        /// <summary>
        /// There are no comments for Property DateCreated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this.OnDateCreatedChanging(value);
                if (object.Equals(this.DateCreated, value))
                {
                    return;
                }
                this._DateCreated = value;
                this.OnDateCreatedChanged();
                this.OnPropertyChanged("DateCreated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _DateCreated;
        partial void OnDateCreatedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateCreatedChanged();
        /// <summary>
        /// There are no comments for Property Mood in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Mood
        {
            get
            {
                return this._Mood;
            }
            set
            {
                this.OnMoodChanging(value);
                if (object.Equals(this.Mood, value))
                {
                    return;
                }
                this._Mood = value;
                this.OnMoodChanged();
                this.OnPropertyChanged("Mood");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Mood;
        partial void OnMoodChanging(global::System.Nullable<int> value);
        partial void OnMoodChanged();
        /// <summary>
        /// There are no comments for Property Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Product
        {
            get
            {
                return this._Product;
            }
            set
            {
                this.OnProductChanging(value);
                if (object.Equals(this.Product, value))
                {
                    return;
                }
                this._Product = value;
                this.OnProductChanged();
                this.OnPropertyChanged("Product");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Product;
        partial void OnProductChanging(string value);
        partial void OnProductChanged();
        /// <summary>
        /// There are no comments for Mood1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Mood Mood1
        {
            get
            {
                this.@__Mood1.EnsureValueInitialized();
                return this._Mood1;
            }
            set
            {
                Mood previous = this.Mood1;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Mood1 = null;
                    this.@__Mood1.OnValueSet();
                    previous.Feedbacks.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Mood = value.ID;
                    }
                    else
                    {
                        this.Mood = default(global::System.Nullable<int>);
                    }
                }
                this._Mood1 = value;
                this.@__Mood1.OnValueSet();
                if ((value != null))
                {
                    value.@__Feedbacks.Add(this);
                }
                this.___OnPropertyChanged("Mood1");
                this.OnPropertyChanged("Mood1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Mood _Mood1;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Message in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Messages")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Message : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Message object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Message CreateMessage(long ID)
        {
            Message message = new Message();
            message.ID = ID;
            return message;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                if (object.Equals(this.ID, value))
                {
                    return;
                }
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property MessageName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MessageName
        {
            get
            {
                return this._MessageName;
            }
            set
            {
                this.OnMessageNameChanging(value);
                if (object.Equals(this.MessageName, value))
                {
                    return;
                }
                this._MessageName = value;
                this.OnMessageNameChanged();
                this.OnPropertyChanged("MessageName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MessageName;
        partial void OnMessageNameChanging(string value);
        partial void OnMessageNameChanged();
        /// <summary>
        /// There are no comments for Property Message1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Message1
        {
            get
            {
                return this._Message1;
            }
            set
            {
                this.OnMessage1Changing(value);
                if (object.Equals(this.Message1, value))
                {
                    return;
                }
                this._Message1 = value;
                this.OnMessage1Changed();
                this.OnPropertyChanged("Message1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Message1;
        partial void OnMessage1Changing(string value);
        partial void OnMessage1Changed();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Mood in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Moods")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Mood : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Mood object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Mood CreateMood(int ID)
        {
            Mood mood = new Mood();
            mood.ID = ID;
            return mood;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                if (object.Equals(this.ID, value))
                {
                    return;
                }
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                if (object.Equals(this.Description, value))
                {
                    return;
                }
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Emoticon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] Emoticon
        {
            get
            {
                if ((this._Emoticon != null))
                {
                    return ((byte[])(this._Emoticon.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnEmoticonChanging(value);
                if (object.Equals(this.Emoticon, value))
                {
                    return;
                }
                this._Emoticon = value;
                this.OnEmoticonChanged();
                this.OnPropertyChanged("Emoticon");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _Emoticon;
        partial void OnEmoticonChanging(byte[] value);
        partial void OnEmoticonChanged();
        /// <summary>
        /// There are no comments for Feedbacks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Feedback> Feedbacks
        {
            get
            {
                this.@__Feedbacks.EnsureValueInitialized();
                return this._Feedbacks;
            }
            set
            {
                this._Feedbacks = value;
                this.OnPropertyChanged("Feedbacks");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Feedback> _Feedbacks = new global::System.Data.Services.Client.DataServiceCollection<Feedback>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
